// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/calculate-love-score.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function calculateLoveScore(name1, name2, loc1, loc2) {
  const combined = (name1.toLowerCase() + name2.toLowerCase()).replace(/\s/g, "");
  let hash = 0;
  for (let i = 0; i < combined.length; i++) {
    hash = (hash << 5) - hash + combined.charCodeAt(i);
    hash = hash & hash;
  }
  let locationBonus = 0;
  if (loc1 && loc2) {
    const distance = Math.sqrt(
      Math.pow(loc2.lat - loc1.lat, 2) + Math.pow(loc2.lng - loc1.lng, 2)
    );
    locationBonus = Math.max(0, 15 - distance * 0.5);
  }
  const baseScore = 35 + Math.abs(hash % 50);
  return Math.min(99, Math.round(baseScore + locationBonus));
}
var calculate_love_score_default = defineTool({
  name: "calculate_love_score",
  title: "Calculate love score",
  description: "Compute a deterministic love-compatibility score (0-99) for two names, optionally boosted by geographic closeness.",
  inputSchema: {
    name1: z.string().min(1).describe("First person's name"),
    name2: z.string().min(1).describe("Second person's name"),
    location1: z.object({ lat: z.number(), lng: z.number() }).optional().describe("Optional latitude/longitude for the first person"),
    location2: z.object({ lat: z.number(), lng: z.number() }).optional().describe("Optional latitude/longitude for the second person")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ name1, name2, location1, location2 }) => {
    const score = calculateLoveScore(name1, name2, location1, location2);
    let verdict = "Just friends";
    if (score >= 85) verdict = "Soulmates";
    else if (score >= 70) verdict = "Strong match";
    else if (score >= 55) verdict = "Promising spark";
    else if (score >= 40) verdict = "Worth exploring";
    return {
      content: [
        {
          type: "text",
          text: `${name1} + ${name2}: ${score}% \u2014 ${verdict}`
        }
      ],
      structuredContent: { score, verdict, name1, name2 }
    };
  }
});

// src/lib/mcp/tools/distance-between.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function haversineKm(a, b) {
  const R = 6371;
  const toRad = (d) => d * Math.PI / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
var distance_between_default = defineTool2({
  name: "distance_between",
  title: "Distance between two locations",
  description: "Return the great-circle distance in kilometers and miles between two lat/lng points.",
  inputSchema: {
    location1: z2.object({ lat: z2.number(), lng: z2.number() }),
    location2: z2.object({ lat: z2.number(), lng: z2.number() })
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ location1, location2 }) => {
    const km = haversineKm(location1, location2);
    const miles = km * 0.621371;
    return {
      content: [
        {
          type: "text",
          text: `${km.toFixed(1)} km (${miles.toFixed(1)} mi)`
        }
      ],
      structuredContent: { kilometers: +km.toFixed(2), miles: +miles.toFixed(2) }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "map-my-heart-mcp",
  title: "Map My Heart MCP",
  version: "0.1.0",
  instructions: "Tools from the Map My Heart love-test app. Use `calculate_love_score` to score compatibility between two names (optionally with locations), and `distance_between` to measure the great-circle distance between two lat/lng points.",
  tools: [calculate_love_score_default, distance_between_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
